# Generated by Django 5.1.15 on 2026-07-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='till_number_used',
        ),
        migrations.AddField(
            model_name='order',
            name='account_number_used',
            field=models.CharField(blank=True, help_text='Company account number shown at checkout time', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='paybill_number_used',
            field=models.CharField(blank=True, help_text='Company Paybill number shown at checkout time', max_length=20),
        ),
    ]
