# Generated by Django 5.1.15 on 2026-07-29 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('in_stock', models.BooleanField(default=True)),
                ('is_on_offer', models.BooleanField(default=False)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extra_specs', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='InductionCookerSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watts', models.PositiveIntegerField(help_text='Power rating in watts, e.g. 2000')),
                ('power_output_levels', models.PositiveIntegerField(help_text='Number of power/heat levels, e.g. 10')),
                ('channel_lock_system', models.CharField(blank=True, help_text="e.g. 'Child lock', 'Touch lock', 'Auto shut-off'", max_length=100)),
                ('voltage', models.CharField(blank=True, max_length=50)),
                ('warranty_months', models.PositiveIntegerField(default=12)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='induction_cooker_spec', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='SufuriaSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(help_text="e.g. '28cm', '5 Litres'", max_length=50)),
                ('material', models.CharField(help_text="e.g. 'Aluminium', 'Stainless Steel'", max_length=100)),
                ('induction_compatible', models.BooleanField(default=False)),
                ('has_lid', models.BooleanField(default=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sufuria_spec', to='products.product')),
            ],
        ),
    ]
