# Generated by Django 5.1.15 on 2026-08-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductioncookerspec',
            name='dimensions',
            field=models.CharField(blank=True, help_text="e.g. '32cm x 28cm x 6cm' (L x W x H)", max_length=100),
        ),
    ]
